손유진/freelec-springboot2-webservice/build.gradle, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/Application.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/HelloController.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/HelloResponseDto.java, 손유진/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/HelloControllerTest.java, 손유진/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/dto/HelloResponseDtoTest.java
- 인텔리제이 설치 및 기본 사용, 깃허브 연동
- TDD, 단위 테스트에 관한 내용
- 테스트 코드 작성
- 롬복 사용법
https://dolgorae.notion.site/Spring-Study-8439bdef9a5f491b852ded0686464c68
=> [손유진] 2021 GDSC Spring Study 입문 - 1주차

유수화/freelec-springboot2-webservice/build.gradle, 유수화/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/Application.java, 유수화/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/BaseTimeEntity.java, 유수화/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/Posts.java, 유수화/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/PostsRepository.java, 유수화/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/service/posts/PostsService.java, 유수화/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/PostsApiController.java, 유수화/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsResponseDto.java, 유수화/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsSaveRequestDto.java, 유수화/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsUpdateRequestDto.java, 유수화/freelec-springboot2-webservice/src/main/resources/application.properties, 유수화/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/domain/posts/PostsRepositoryTest.java, 유수화/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/PostsApiControllerTest.java
스프링 부트에서 JPA를 사용하여 데이터베이스의 쿼리와 데이블들을 객체지향에 맞게 다뤄보는 시간을 가졌다.
어디 보여주기 부끄러운 노트정리라서... 조금더 깔끔하게 정리하고 담주에 링크 올리겠습니다.....
=> [유수화] 2021 GDSC Spring Study 입문 - 2주차

류현지/freelec-springboot2-webservice/build.gradle, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/Application.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/domain/BaseTimeEntity.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/domain/posts/PostRepository.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/domain/posts/Posts.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/service/posts/PostsService.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/web/PostsApiController.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/web/dto/PostsResponseDto.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/web/dto/PostsSaveRequestDto.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/web/dto/PostsUpdateRequestDto.java, 류현지/freelec-springboot2-webservice/src/main/resources/application.properties, 류현지/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/freelecspringboot2webservice/web/PostsApiControllerTest.java, 류현지/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/freelecspringboot2webservice/web/domain/posts/PostRepositoryTest.java
*JPA*와 Spring JPA (+영속성 컨텍스트), 관계형 데이터베이스 관리, Auditing
https://defiant-coat-2e2.notion.site/Chap3-JPA-3a7ef5566a9e4bab96597dc8709b2957
REST API랑 HTTP 메소드, 웹 계층과 패키지 구조
공부 하면 할수록 더 할게 늘어나는거 같아요...............
=> [류현지] 2022 GDSC Spring Study 입문 - 2주차

윤혜경/freelec-springboot2-webservice/build.gradle, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/FreelecSpringboot2WebserviceApplication.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/domain/BaseTimeEntity.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/domain/posts/Posts.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/domain/posts/PostsRepository.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/service/posts/PostsService.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/web/PostsApiController.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/web/dto/PostsResponseDto.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/web/dto/PostsSaveRequestDto.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/web/dto/PostsUpdateRequestDto.java, 윤혜경/freelec-springboot2-webservice/src/main/resources/application.properties, 윤혜경/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/freelecspringboot2webservice/domain/posts/PostsRepositoryTest.java, 윤혜경/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/freelecspringboot2webservice/web/PostsApiControllerTest.java
JPA 개념 및 프로젝트 적용, 테스트 코드 작성
API 만들기
JPA Auditing으로 하는 자동화
1주차에 작성하였으나 이번주는 어려울 것 같아서 다음에 정리해서 올려보도록 하겠습니다…!
=> [윤혜경] 2022 GDSC Spring Study 입문 - 2주차

김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/Application.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/domain/BaseTimeEntity.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/domain/posts/Posts.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/domain/posts/PostsRepository.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/service/posts/PostsService.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/web/PostsApiController.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/web/dto/PostsResponseDto.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/web/dto/PostsSaveRequestDto.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/web/dto/PostsUpdateRequestDto.java, 김수빈/freelec-springboot2-websevice/src/main/resources/application.properties, 김수빈/freelec-springboot2-websevice/src/test/java/com/book/springboot/domain/posts/PostsRepositoryTest.java, 김수빈/freelec-springboot2-websevice/src/test/java/com/book/springboot/web/PostsApiControllerTest.java
[x] Spring Data JPA 적용
[x] 등록/수정/조회 API 작성
[x] JPA Auditing으로 생성시간/수정시간 자동화
=> [김수빈] 2022 GDSC Spring Study 입문 - 2주차

윤이빈/freelec-springboot2-webservice/build.gradle, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/Application.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/BaseTimeEntity.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/Posts.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/PostsRepository.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/service/posts/PostsService.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/PostsApiController.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsResponseDto.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsSaveRequestDto.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsUpdateRequestDto.java, 윤이빈/freelec-springboot2-webservice/src/main/resources/application.properties, 윤이빈/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/domain/posts/PostsRepositoryTest.java, 윤이빈/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/PostsApiControllerTest.java
Spring Data JPA로 Spring boot에서 관계형 데이터베이스를 사용하는 법
Entity, Repository, Dto, Controller, Service 등을 작성하고 테스트 코드로 테스트하는 법
- 등록/수정/조회 API 만들기
- 생성시간/수정시간 자동화하기
JPA
=> [윤이빈] 2022 GDSC Spring Study 입문 - 2주차

윤다빈/freelec-springboot2-webservice/.idea/gradle.xml, 윤다빈/freelec-springboot2-webservice/build.gradle, 윤다빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/Application.java, 윤다빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/BaseTimeEntity.java, 윤다빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/Posts.java, 윤다빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/PostsRepository.java, 윤다빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/service/posts/PostsService.java, 윤다빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/PostsApiController.java, 윤다빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsResponseDto.java, 윤다빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsSaveRequestDto.java, 윤다빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsUpdateRequestDto.java, 윤다빈/freelec-springboot2-webservice/src/main/resources/application.properties, 윤다빈/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/domain/posts/PostsRepositoryTest.java, 윤다빈/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/PostsApiControllerTest.java, 윤다빈/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/domain/posts/PostsRepositoryTest.java
- JPA와 Spring Data JPA
- 스프링의 웹 계층
- 등록, 수정, 조회 API 생성
- JPA Auditing
https://pickle-fireplant-fa1.notion.site/2-d036f52794474e33b5e4460f728773cd
=> [윤다빈] 2022 GDSC Spring Study 입문 - 2주차

손유진/freelec-springboot2-webservice/build.gradle, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/Application.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/BaseTimeEntity.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/Posts.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/PostsRepository.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/service/posts/PostsService.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/PostApiController.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/PostsApiController.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsResponseDto.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsSaveRequestDto.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsUpdateRequestDto.java, 손유진/freelec-springboot2-webservice/src/main/resources/application.properties, 손유진/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/domain/posts/PostsRepositoryTest.java, 손유진/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/PostsApiControllerTest.java
- JPA란? / Spring Data JPA 적용법
- Spring 웹 계층
- 등록/수정/조회 API
- h2 콘솔 사용
- JPA Auditing
https://dolgorae.notion.site/JPA-906f536d3ef4416bb533831b57bf7549
=> [손유진] 2022 GDSC Spring Study 입문 - 2주차

.idea/.gitignore, .idea/2022-02-Spring-Novice-Study.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, 황연진/gdsc-springboot-study/.gitignore, 황연진/gdsc-springboot-study/build.gradle, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/GdscSpringbootStudyApplication.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/domain/BaseTimeEntity.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/domain/posts/Posts.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/domain/posts/PostsRepository.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/service/posts/PostsService.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/web/PostsApiController.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/web/dto/PostsResponseDto.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/web/dto/PostsSaveRequestDto.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/web/dto/PostsUpdateRequestDto.java, 황연진/gdsc-springboot-study/src/main/resources/application.properties, 황연진/gdsc-springboot-study/src/test/java/com/gdsc/study/gdscspringbootstudy/domain/posts/PostsRepositoryTest.java, 황연진/gdsc-springboot-study/src/test/java/com/gdsc/study/gdscspringbootstudy/web/PostsApiControllerTest.java
https://www.notion.so/yeoncheong/2-91d77029ef1e42b2a573ec513d7b31aa
=> [황연진] 2022 GDSC Spring Study 입문 - 2주차

황연진/gdsc-springboot-study/build.gradle, 황연진/gdsc-springboot-study/build/resources/main/application.properties, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/domain/posts/PostsRepository.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/service/posts/PostsService.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/web/IndexController.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/web/PostsApiController.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/web/dto/PostsListResponseDto.java, 황연진/gdsc-springboot-study/src/main/resources/static/js/app/index.js, 황연진/gdsc-springboot-study/src/main/resources/templates/index.mustache, 황연진/gdsc-springboot-study/src/main/resources/templates/layout/footer.mustache, 황연진/gdsc-springboot-study/src/main/resources/templates/layout/header.mustache, 황연진/gdsc-springboot-study/src/main/resources/templates/posts-save.mustache, 황연진/gdsc-springboot-study/src/main/resources/templates/posts-update.mustache, 황연진/gdsc-springboot-study/src/test/java/com/gdsc/study/gdscspringbootstudy/domain/posts/PostsRepositoryTest.java, 황연진/gdsc-springboot-study/src/test/java/com/gdsc/study/gdscspringbootstudy/web/IndexControllerTest.java, 황연진/gdsc-springboot-study/src/test/java/com/gdsc/study/gdscspringbootstudy/web/PostsApiControllerTest.java
https://www.notion.so/yeoncheong/3-40d5d47235494861a4c7d1d84eb7daa1
=> [황연진] 2022 GDSC Spring Study 입문 - 3주차

윤이빈/freelec-springboot2-webservice/build.gradle, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/PostsRepository.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/service/posts/PostsService.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/IndexController.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/PostsApiController.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsListResponseDto.java, 윤이빈/freelec-springboot2-webservice/src/main/resources/static/js/app/index.js, 윤이빈/freelec-springboot2-webservice/src/main/resources/templates/index.mustache, 윤이빈/freelec-springboot2-webservice/src/main/resources/templates/layout/footer.mustache, 윤이빈/freelec-springboot2-webservice/src/main/resources/templates/layout/header.mustache, 윤이빈/freelec-springboot2-webservice/src/main/resources/templates/posts-save.mustache, 윤이빈/freelec-springboot2-webservice/src/main/resources/templates/posts-update.mustache, 윤이빈/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/IndexControllerTest.java
- mustache 기본 사용법
- 게시글 등록, 조회, 수정/삭제 화면 구현
- postman으로 api 테스트
=> [윤이빈] 2022 GDSC Spring Study 입문 - 3주차

손유진/freelec-springboot2-webservice/build.gradle, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/posts/PostsRepository.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/service/posts/PostsService.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/IndexController.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/PostsApiController.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/dto/PostsListResponseDto.java, 손유진/freelec-springboot2-webservice/src/main/resources/application.properties, 손유진/freelec-springboot2-webservice/src/main/resources/static/js/app/index.js, 손유진/freelec-springboot2-webservice/src/main/resources/templates/index.mustache, 손유진/freelec-springboot2-webservice/src/main/resources/templates/layout/footer.mustache, 손유진/freelec-springboot2-webservice/src/main/resources/templates/layout/header.mustache, 손유진/freelec-springboot2-webservice/src/main/resources/templates/posts-save.mustache, 손유진/freelec-springboot2-webservice/src/main/resources/templates/posts-update.mustache, 손유진/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/IndexControllerTest.java
- mustache 사용법
- 게시글 등록, 조회, 수정, 삭제 화면 구성
- postman 사용법
- 게시글 등록
- 게시글 목록 조회
- 게시글 수정
- 게시글 삭제
=> [손유진] 2022 GDSC Spring Study 입문 - 3주차

한채연/freelec-springboot2-webservice/build.gradle, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/domain/posts/PostsRepository.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/service/posts/PostsService.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/web/IndexController.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/web/PostsApiController.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/web/dto/PostsListResponseDto.java, 한채연/freelec-springboot2-webservice/src/main/resources/static/js/app/index.js, 한채연/freelec-springboot2-webservice/src/main/resources/templates/index.mustache, 한채연/freelec-springboot2-webservice/src/main/resources/templates/layout/footer.mustache, 한채연/freelec-springboot2-webservice/src/main/resources/templates/layout/header.mustache, 한채연/freelec-springboot2-webservice/src/main/resources/templates/posts-save.mustache, 한채연/freelec-springboot2-webservice/src/main/resources/templates/posts-update.mustache, 한채연/freelec-springboot2-webservice/src/test/java/com/hcy/book/springboot/web/IndexControllerTest.java
https://natural-need-ea3.notion.site/3-2f946d1ee6384a09b90105856b131af9
=> [한채연] 2022 GDSC Spring Study 입문 - 3주차

김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/domain/posts/Posts.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/domain/posts/PostsRepository.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/service/posts/PostsService.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/web/IndexController.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/web/PostsApiController.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/web/dto/PostsListResponseDto.java, 김수빈/freelec-springboot2-websevice/src/main/resources/static/js/app/index.js, 김수빈/freelec-springboot2-websevice/src/main/resources/templates/index.mustache, 김수빈/freelec-springboot2-websevice/src/main/resources/templates/layout/footer.mustache, 김수빈/freelec-springboot2-websevice/src/main/resources/templates/layout/header.mustache, 김수빈/freelec-springboot2-websevice/src/main/resources/templates/posts-save.mustache, 김수빈/freelec-springboot2-websevice/src/test/java/com/book/springboot/web/IndexControllerTest.java, 김수빈/freelec-springboot2-websevice/src/test/java/com/book/springboot/web/PostsApiControllerTest.java
mustache로 화면 구현 후 postman을 통한 실습
테스트 화면 스크린샷 링크 - https://thinkable-handstand-dec.notion.site/8ae03c573b7d4f959a66252afb4668ae
=> [김수빈] 2022 GDSC Spring Study 입문 - 3주차

박소윤/freelec-springboot2-webservice/build.gradle, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/FreelecSpringboot2WebserviceApplication.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/domain/posts/PostsRepository.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/service/posts/PostsService.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/web/IndexController.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/web/PostsApiController.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/web/dto/PostsListResponseDto.java, 박소윤/freelec-springboot2-webservice/src/main/resources/static/js/app/index.js, 박소윤/freelec-springboot2-webservice/src/main/resources/templates/index.mustache, 박소윤/freelec-springboot2-webservice/src/main/resources/templates/layout/footer.mustache, 박소윤/freelec-springboot2-webservice/src/main/resources/templates/layout/header.mustache, 박소윤/freelec-springboot2-webservice/src/main/resources/templates/posts-save.mustache, 박소윤/freelec-springboot2-webservice/src/main/resources/templates/posts-update.mustache, 박소윤/freelec-springboot2-webservice/src/test/java/com/gdsc/freelecspringboot2webservice/web/IndexControllerTest.java, 박소윤/freelec-springboot2-webservice/src/test/java/com/gdsc/freelecspringboot2webservice/web/PostsApiControllerTest.java
- 서버 템플릿 엔진이란?
- 머스테치란?
- 머스테치로 CRUD 구현하기
[3주차 스터디 정리글](https://happine2s.notion.site/3-b836c2cabc264c5eb4e6986875e60454)
넥스트도 공부할 계획이라서 그런지 js 공부가 부족한게 너무 실감났다 ㅠㅠ
js의 최적화된 위치 선정으로 웹 사이트의 로딩 속도를 향상시키는 개발자가 되고싶다
=> [박소윤] 2022 GDSC Spring Study 입문 - 3주차

윤혜경/freelec-springboot2-webservice/.gitignore, 윤혜경/freelec-springboot2-webservice/build.gradle, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/FreelecSpringboot2WebserviceApplication.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/JpaConfig.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/WebConfig.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/auth/CustomOAuth2UserService.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/auth/LoginUser.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/auth/LoginUserArgumentResolvr.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/auth/SecurityConfig.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/auth/dto/OAuthAttributes.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/auth/dto/SessionUser.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/domain/user/Role.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/domain/user/User.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/domain/user/UserRepository.java, 윤혜경/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/web/IndexController.java, 윤혜경/freelec-springboot2-webservice/src/main/resources/application-oauth.properties, 윤혜경/freelec-springboot2-webservice/src/main/resources/application.properties, 윤혜경/freelec-springboot2-webservice/src/main/resources/templates/index.mustache, 윤혜경/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/freelecspringboot2webservice/web/HelloControllerTest.java, 윤혜경/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/freelecspringboot2webservice/web/PostsApiControllerTest.java, 윤혜경/freelec-springboot2-webservice/src/test/resources/application.properties
spring security를 사용해서 구글과 네이버 로그인 하기
session storage DB 사용하기
ArgumentResolver로 로그인 session 정보 가져오기
테스트 코드 오류 해결
— 소셜 로그인에 성공한 페이지 —
<!--블로그나 노션에 실습 내용을 정리했다면 링크를 첨부해주세요!(필수 X)—>
=> [윤혜경] 2022 GDSC Spring Study 입문 - 4주차

황연진/gdsc-springboot-study/.gitignore, 황연진/gdsc-springboot-study/build.gradle, 황연진/gdsc-springboot-study/build/resources/main/application.properties, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/GdscSpringbootStudyApplication.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/config/JpaConfig.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/config/WebConfig.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/config/auth/CustomOAuth2UserService.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/config/auth/LoginUser.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/config/auth/LoginUserArgumentResolver.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/config/auth/SecurityConfig.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/config/auth/dto/OAuthAttributes.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/config/auth/dto/SessionUser.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/domain/user/Role.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/domain/user/User.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/domain/user/UserRepository.java, 황연진/gdsc-springboot-study/src/main/java/com/gdsc/study/gdscspringbootstudy/web/IndexController.java, 황연진/gdsc-springboot-study/src/main/resources/application.properties, 황연진/gdsc-springboot-study/src/main/resources/templates/index.mustache, 황연진/gdsc-springboot-study/src/test/java/com/gdsc/study/gdscspringbootstudy/web/HelloControllerTest.java, 황연진/gdsc-springboot-study/src/test/java/com/gdsc/study/gdscspringbootstudy/web/PostsApiControllerTest.java, 황연진/gdsc-springboot-study/src/test/resources/application.properties
https://www.notion.so/yeoncheong/4-7b2b01f0a0ce4b05966ffe6f484742a5
로그인 성공 사진 링크입니다.
=> [황연진] 2022 GDSC Spring Study 입문 - 4주차

한채연/freelec-springboot2-webservice/.gitignore, 한채연/freelec-springboot2-webservice/build.gradle, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/Application.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/config/JpaConfig.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/config/WebConfig.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/config/auth/CustomOAuth2UserService.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/config/auth/LoginUser.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/config/auth/LoginUserArgumentResolver.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/config/auth/SecurityConfig.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/config/auth/dto/OAuthAttributes.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/config/auth/dto/SessionUser.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/domain/user/Role.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/domain/user/User.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/domain/user/UserRepository.java, 한채연/freelec-springboot2-webservice/src/main/java/com/hcy/book/springboot/web/IndexController.java, 한채연/freelec-springboot2-webservice/src/main/resources/application.properties, 한채연/freelec-springboot2-webservice/src/main/resources/templates/index.mustache, 한채연/freelec-springboot2-webservice/src/test/java/com/hcy/book/springboot/web/HelloControllerTest.java, 한채연/freelec-springboot2-webservice/src/test/java/com/hcy/book/springboot/web/PostsApiControllerTest.java
https://natural-need-ea3.notion.site/4-8a98cc77c67845fb82aabfbecc740e84
시큐리티 내부 동작 원리에 대해 좀 더 깊게 공부해보고 싶어요! (뭔가 휘리릭 넘어간 느낌이라..)
왜 시큐리티는 공부할수록 더 어려울까요.......?😇😇
=> [한채연] 2022 GDSC Spring Study 입문 - 4주차

류현지/freelec-springboot2-webservice/build.gradle, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/Application.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/JpaConfig.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/WebConfig.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/auth/CustomOAuth2UserService.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/auth/LoginUser.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/auth/LoginUserArgumentResolver.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/auth/SecurityConfig.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/auth/dto/OAuthAttributes.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/config/auth/dto/SessionUser.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/domain/user/Role.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/domain/user/User.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/domain/user/UserRepository.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/web/IndexController.java, 류현지/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/freelecspringboot2webservice/web/dto/IndexController.java, 류현지/freelec-springboot2-webservice/src/main/resources/application.properties, 류현지/freelec-springboot2-webservice/src/main/resources/templates/index.mustache, 류현지/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/freelecspringboot2webservice/web/HelloControllerTest.java, 류현지/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/freelecspringboot2webservice/web/PostsApiControllerTest.java, 류현지/freelec-springboot2-webservice/src/test/resources/application.properties
- 스프링 시큐리티
- 시큐리티를 이용한 구글 로그인 연동 / 네이버 로그인 연동
- 새션 초기화 관련 -> 세션 저장소 비교 (톰캣 (내부) vs DB 사용)
- 어노테이션을 이용해 로그인 세션 정보 간단 가져오기 (ArgumentResolver)
- 시큐리티로 인한 API 테스트 코드의 전반적 수정 (Role 관련 문제)
https://defiant-coat-2e2.notion.site/Chap5-OAuth-2-0-e0b7454f061d4132bc35b1528dec1f44
전반적으로 다시 한번 복습해야 할 것 같습니다ㅎㅎ...
=> [류현지] 2021 GDSC Spring Study 입문 - 4주차

한비/freelec-springboot2-webservice/src/main/resources/templates/index.mustache
스프링 시큐티리로 구글, 네이버 연동 로그인 기능 구현하기
=> [김한비] 2022 GDSC Spring Study 입문 - 4주차

윤이빈/freelec-springboot2-webservice/.gitignore, 윤이빈/freelec-springboot2-webservice/build.gradle, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/Application.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/JpaConfig.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/WebConfig.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/auth/CustomOAuth2UserService.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/auth/LoginUser.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/auth/LoginUserArgumentResolver.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/auth/SecurityConfig.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/auth/dto/OAuthAttributes.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/auth/dto/SessionUser.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/user/Role.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/user/User.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/user/UserRepository.java, 윤이빈/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/IndexController.java, 윤이빈/freelec-springboot2-webservice/src/main/resources/application.properties, 윤이빈/freelec-springboot2-webservice/src/main/resources/templates/index.mustache, 윤이빈/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/HelloControllerTest.java, 윤이빈/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/PostsApiControllerTest.java, 윤이빈/freelec-springboot2-webservice/src/test/resources/application.properties
- 스프링 시큐리티를 이용해서 구글/네이버 로그인 연동
- 스프링 시큐리티 적용 시 테스트 코드 작성법
=> [윤이빈] 2022 GDSC Spring Study 입문 - 4주차

박소윤/freelec-springboot2-webservice/.gitignore, 박소윤/freelec-springboot2-webservice/build.gradle, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/config/WebConfig.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/config/auth/CustomOAuth2UserService.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/config/auth/LoginUser.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/config/auth/LoginUserArgumentResolver.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/config/auth/SecurityConfig.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/config/auth/dto/OAuthAttributes.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/config/auth/dto/SessionUser.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/domain/user/Role.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/domain/user/User.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/domain/user/UserRepository.java, 박소윤/freelec-springboot2-webservice/src/main/java/com/gdsc/freelecspringboot2webservice/web/IndexController.java, 박소윤/freelec-springboot2-webservice/src/main/resources/application.properties, 박소윤/freelec-springboot2-webservice/src/main/resources/templates/index.mustache
- 소셜 로그인 구현하기: `Google`, `Naver`
- 어노테이션 이반으로 개선하기
- 세션 저장소로 DB 사용하기
[4주차 스터디 정리글](https://happine2s.notion.site/4-Oauth-2-0-698a5af23cc84fa2848780d00aa7ea6e)
역대급으로 버전차이 확 느꼈다... 테스트코드 아예 실행이 안돼서 대체 함수 찾다가 도저히 못하겠어서 포기했다.
로그인 구현하면서 특히 객체끼리의 관계를 이해하는게 가장 어려웠다.
아직도 유저 어노테이션 생성한건 이해가 잘 안간다.
=> [박소윤] 2022 GDSC Spring Study 입문 - 4주차

김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/Application.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/config/JpaConfig.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/config/WebConfig.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/config/auth/CustomOAuth2UserService.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/config/auth/LoginUser.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/config/auth/LoginUserArgumentResolver.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/config/auth/SecurityConfig.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/config/auth/dto/OAuthAttributes.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/config/auth/dto/SessionUser.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/domain/user/Role.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/domain/user/User.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/domain/user/UserRepository.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/web/IndexController.java, 김수빈/freelec-springboot2-websevice/src/main/java/com/book/springboot/web/PostsApiController.java, 김수빈/freelec-springboot2-websevice/src/main/resources/templates/index.mustache, 김수빈/freelec-springboot2-websevice/src/test/java/com/book/springboot/web/HelloControllerTest.java, 김수빈/freelec-springboot2-websevice/src/test/java/com/book/springboot/web/PostsApiControllerTest.java
- 스프링 시큐리티, Oauth2로 로그인 기능 구현하기
- 구글, 네이버 로그인 연동하기
다시 복습해서 노션에 정리하기...
=> [김수빈] 2022 GDSC Spring Study 입문 - 4주차

손유진/freelec-springboot2-webservice/.gitignore, 손유진/freelec-springboot2-webservice/build.gradle, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/Application.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/JpaConfig.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/WebConfig.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/auth/CustomOAuth2UserService.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/auth/LoginUser.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/auth/LoginUserArgumentResolver.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/auth/SecurityConfig.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/auth/dto/OAuthAttributes.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/config/auth/dto/SessionUser.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/user/Role.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/user/User.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/domain/user/UserRepository.java, 손유진/freelec-springboot2-webservice/src/main/java/com/jojoldu/book/springboot/web/IndexController.java, 손유진/freelec-springboot2-webservice/src/main/resources/application.properties, 손유진/freelec-springboot2-webservice/src/main/resources/templates/index.mustache, 손유진/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/HelloControllerTest.java, 손유진/freelec-springboot2-webservice/src/test/java/com/jojoldu/book/springboot/web/PostsApiControllerTest.java, 손유진/freelec-springboot2-webservice/src/test/resources/application.properties
- OAuth2 사용하여 로그인 기능 구현
- 구글, 네이버 서비스 등록 방법
- 스프링 시큐리티 설정
- 코드 개선 -어노테이션 활용
- 테스트 문제 해결 - 시큐리티 적용
=> [손유진] 2022 GDSC Spring Study 입문 - 4주차

.idea/.gitignore, .idea/2022-02-Spring-Novice-Study.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, 최다영/.idea/.gitignore, 최다영/.idea/modules.xml, 최다영/.idea/vcs.xml, 최다영/.idea/최다영.iml, 최다영/springProject-1/.gitignore, 최다영/springProject-1/build.gradle, 최다영/springProject-1/src/main/java/com/example/springProject1/Application.java, 최다영/springProject-1/src/main/java/com/example/springProject1/config/JpaConfig.java, 최다영/springProject-1/src/main/java/com/example/springProject1/config/WebConfig.java, 최다영/springProject-1/src/main/java/com/example/springProject1/config/auth/CustomOAuth2UserService.java, 최다영/springProject-1/src/main/java/com/example/springProject1/config/auth/LoginUser.java, 최다영/springProject-1/src/main/java/com/example/springProject1/config/auth/LoginUserArgumentResolver.java, 최다영/springProject-1/src/main/java/com/example/springProject1/config/auth/SecurityConfig.java, 최다영/springProject-1/src/main/java/com/example/springProject1/config/auth/dto/OAuthAttributes.java, 최다영/springProject-1/src/main/java/com/example/springProject1/config/auth/dto/SessionUser.java, 최다영/springProject-1/src/main/java/com/example/springProject1/domain/BaseTimeEntity.java, 최다영/springProject-1/src/main/java/com/example/springProject1/web/HelloController.java, 최다영/springProject-1/src/main/java/com/example/springProject1/web/IndexController.java, 최다영/springProject-1/src/main/resources/application.properties, 최다영/springProject-1/src/main/resources/templates/index.mustache, 최다영/springProject-1/src/test/java/com/example/springProject1/domain/posts/PostsRepositoryTest.java, 최다영/springProject-1/src/test/java/com/example/springProject1/dto/HelloResponseDtoTest.java, 최다영/springProject-1/src/test/java/com/example/springProject1/web/HelloControllerTest.java, 최다영/springProject-1/src/test/java/com/example/springProject1/web/IndexControllerTest.java, 최다영/springProject-1/src/test/java/com/example/springProject1/web/PostsApiControllerTest.java
- 스프링 시큐리티와 스프링 시큐리티 Oauth2클라이언트
- 구글 서비스 등록
- 구글 로그인 연동
- 어노테이션 기반 개선
- 세션 저장소로 데이터베이스 사용
- 네이버 로그인
- 기존 테스트에 시큐리티 적용
=> [최다영] 2022 GDSC Spring Study 입문 - 4주차

문유진/스터디에 임하는 각오.md
=> [문유진] 2022 GDSC Spring Study 입문 - 5주차

류현지/스터디에 임하는 각오.md
- AWS 서비스 (클라우드 서비스)에 대해
- AWS에 서버 환경 만들기 : 가상 서버 EC2 서비스 생성 및 설정 세팅
- AWS에 데이터베이스 환경 만들기 : 관리형 데이터베이스 RDS 서비스 생성 및 설정 세팅
- EC2와 RDS 연동하기
https://defiant-coat-2e2.notion.site/Chap-6-AWS-dc2aaaa94f4c4a129bce73c71f858c31
가상화 서비스의 원리
=> [류현지] 2021 GDSC Spring Study 입문 - 5주차

류현지/freelec-springboot2-webservice/build.gradle, 류현지/freelec-springboot2-webservice/src/main/resources/application-real.properties, 류현지/freelec-springboot2-webservice/src/main/resources/application.properties, 류현지/freelec-springboot2-webservice/src/test/resources/application.properties, 류현지/스터디에 임하는 각오.md, 류현지/인스턴스 도메인.md
EC2 인스턴스에 어플리케이션 배포 및 소셜 로그인 등록
(+ 쉘 스크립트, jar 생성, 기타 리눅스 명령어....
https://defiant-coat-2e2.notion.site/Chap8-EC2-b14bdd7e101c48b3954d374ceffc29a3
졸면서 코딩하면 안 하느니만 못하다는 것을 절실히 깨달은 주차네요.....
=> [류현지] 2021 GDSC Spring Study 입문 - 6주차

yundabin/EC2 인스턴스 도메인.md
6주차 EC2 인스턴스 도메인을 안올려서 추가했습니다!
RDS 연결에서 우당탕탕하느라 매우 늦었습니다 ㅜㅜ 죄송해요!
=> [윤다빈] 2022 GDSC Spring Study 입문 - 6주차
